#!/bin/bash

COUNT=0
CURRENT_DIR="$PWD"
PD="device/samsung/kyleprods/patches"
PATCHES=(
'build				build.diff'
'external/icu                   external_icu.diff'
'external/tinyalsa              external_tinyalsa.diff'
'frameworks/av			frameworks_av.diff'
'frameworks/base		frameworks_base.diff'
'frameworks/native		frameworks_native.diff'
'frameworks/opt/net/wifi	frameworks_opt_net_wifi.diff'
'frameworks/opt/telephony	frameworks_opt_telephony.diff'
'hardware/broadcom/libbt	hardware_broadcom_libbt.diff'
'hardware/libhardware_legacy    hardware_libhardware_legacy.diff'
'system/core			system_core.diff'
)

while [ "x${PATCHES[COUNT]}" != "x" ]
do
	CURRENT="${PATCHES[COUNT]}"
	FOLDER=`echo "$CURRENT" | awk '{print $1}'`
	PATCH=`echo "$CURRENT" | awk '{print $2}'`

	cd "$FOLDER"
	echo Patching "$FOLDER" ...
	patch -p1 < "$CURRENT_DIR/$PD/$PATCH"
	cd "$CURRENT_DIR"

	COUNT=$(($COUNT + 1))
patch -p1 < device/samsung/kyleprods/*.diff
done
